/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuresRouteRouteImport } from './routes/structures/route'
import { Route as IndustryHubsRouteRouteImport } from './routes/industry-hubs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StructuresIndexRouteImport } from './routes/structures/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as IndustryHubsIndexRouteImport } from './routes/industry-hubs/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as StructuresStructureIdRouteRouteImport } from './routes/structures_/$structureId.route'
import { Route as IndustryHubsIndustryHubIdRouteRouteImport } from './routes/industry-hubs_/$industryHubId.route'
import { Route as StructuresStructureIdIndexRouteImport } from './routes/structures_/$structureId.index'
import { Route as IndustryHubsIndustryHubIdIndexRouteImport } from './routes/industry-hubs_/$industryHubId.index'

const StructuresRouteRoute = StructuresRouteRouteImport.update({
  id: '/structures',
  path: '/structures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHubsRouteRoute = IndustryHubsRouteRouteImport.update({
  id: '/industry-hubs',
  path: '/industry-hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresIndexRoute = StructuresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StructuresRouteRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHubsIndexRoute = IndustryHubsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustryHubsRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresStructureIdRouteRoute =
  StructuresStructureIdRouteRouteImport.update({
    id: '/structures_/$structureId',
    path: '/structures/$structureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryHubsIndustryHubIdRouteRoute =
  IndustryHubsIndustryHubIdRouteRouteImport.update({
    id: '/industry-hubs_/$industryHubId',
    path: '/industry-hubs/$industryHubId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StructuresStructureIdIndexRoute =
  StructuresStructureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StructuresStructureIdRouteRoute,
  } as any)
const IndustryHubsIndustryHubIdIndexRoute =
  IndustryHubsIndustryHubIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IndustryHubsIndustryHubIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/industry-hubs': typeof IndustryHubsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/industry-hubs/$industryHubId': typeof IndustryHubsIndustryHubIdRouteRouteWithChildren
  '/structures/$structureId': typeof StructuresStructureIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AboutIndexRoute
  '/industry-hubs/': typeof IndustryHubsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/industry-hubs/$industryHubId/': typeof IndustryHubsIndustryHubIdIndexRoute
  '/structures/$structureId/': typeof StructuresStructureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AboutIndexRoute
  '/industry-hubs': typeof IndustryHubsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/structures': typeof StructuresIndexRoute
  '/industry-hubs/$industryHubId': typeof IndustryHubsIndustryHubIdIndexRoute
  '/structures/$structureId': typeof StructuresStructureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/industry-hubs': typeof IndustryHubsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/industry-hubs_/$industryHubId': typeof IndustryHubsIndustryHubIdRouteRouteWithChildren
  '/structures_/$structureId': typeof StructuresStructureIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about/': typeof AboutIndexRoute
  '/industry-hubs/': typeof IndustryHubsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/industry-hubs_/$industryHubId/': typeof IndustryHubsIndustryHubIdIndexRoute
  '/structures_/$structureId/': typeof StructuresStructureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/industry-hubs'
    | '/structures'
    | '/industry-hubs/$industryHubId'
    | '/structures/$structureId'
    | '/auth/login'
    | '/about'
    | '/industry-hubs/'
    | '/legal'
    | '/structures/'
    | '/industry-hubs/$industryHubId/'
    | '/structures/$structureId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/about'
    | '/industry-hubs'
    | '/legal'
    | '/structures'
    | '/industry-hubs/$industryHubId'
    | '/structures/$structureId'
  id:
    | '__root__'
    | '/'
    | '/industry-hubs'
    | '/structures'
    | '/industry-hubs_/$industryHubId'
    | '/structures_/$structureId'
    | '/auth/login'
    | '/about/'
    | '/industry-hubs/'
    | '/legal/'
    | '/structures/'
    | '/industry-hubs_/$industryHubId/'
    | '/structures_/$structureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndustryHubsRouteRoute: typeof IndustryHubsRouteRouteWithChildren
  StructuresRouteRoute: typeof StructuresRouteRouteWithChildren
  IndustryHubsIndustryHubIdRouteRoute: typeof IndustryHubsIndustryHubIdRouteRouteWithChildren
  StructuresStructureIdRouteRoute: typeof StructuresStructureIdRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AboutIndexRoute: typeof AboutIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structures': {
      id: '/structures'
      path: '/structures'
      fullPath: '/structures'
      preLoaderRoute: typeof StructuresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hubs': {
      id: '/industry-hubs'
      path: '/industry-hubs'
      fullPath: '/industry-hubs'
      preLoaderRoute: typeof IndustryHubsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures/': {
      id: '/structures/'
      path: '/'
      fullPath: '/structures/'
      preLoaderRoute: typeof StructuresIndexRouteImport
      parentRoute: typeof StructuresRouteRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hubs/': {
      id: '/industry-hubs/'
      path: '/'
      fullPath: '/industry-hubs/'
      preLoaderRoute: typeof IndustryHubsIndexRouteImport
      parentRoute: typeof IndustryHubsRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures_/$structureId': {
      id: '/structures_/$structureId'
      path: '/structures/$structureId'
      fullPath: '/structures/$structureId'
      preLoaderRoute: typeof StructuresStructureIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hubs_/$industryHubId': {
      id: '/industry-hubs_/$industryHubId'
      path: '/industry-hubs/$industryHubId'
      fullPath: '/industry-hubs/$industryHubId'
      preLoaderRoute: typeof IndustryHubsIndustryHubIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures_/$structureId/': {
      id: '/structures_/$structureId/'
      path: '/'
      fullPath: '/structures/$structureId/'
      preLoaderRoute: typeof StructuresStructureIdIndexRouteImport
      parentRoute: typeof StructuresStructureIdRouteRoute
    }
    '/industry-hubs_/$industryHubId/': {
      id: '/industry-hubs_/$industryHubId/'
      path: '/'
      fullPath: '/industry-hubs/$industryHubId/'
      preLoaderRoute: typeof IndustryHubsIndustryHubIdIndexRouteImport
      parentRoute: typeof IndustryHubsIndustryHubIdRouteRoute
    }
  }
}

interface IndustryHubsRouteRouteChildren {
  IndustryHubsIndexRoute: typeof IndustryHubsIndexRoute
}

const IndustryHubsRouteRouteChildren: IndustryHubsRouteRouteChildren = {
  IndustryHubsIndexRoute: IndustryHubsIndexRoute,
}

const IndustryHubsRouteRouteWithChildren =
  IndustryHubsRouteRoute._addFileChildren(IndustryHubsRouteRouteChildren)

interface StructuresRouteRouteChildren {
  StructuresIndexRoute: typeof StructuresIndexRoute
}

const StructuresRouteRouteChildren: StructuresRouteRouteChildren = {
  StructuresIndexRoute: StructuresIndexRoute,
}

const StructuresRouteRouteWithChildren = StructuresRouteRoute._addFileChildren(
  StructuresRouteRouteChildren,
)

interface IndustryHubsIndustryHubIdRouteRouteChildren {
  IndustryHubsIndustryHubIdIndexRoute: typeof IndustryHubsIndustryHubIdIndexRoute
}

const IndustryHubsIndustryHubIdRouteRouteChildren: IndustryHubsIndustryHubIdRouteRouteChildren =
  {
    IndustryHubsIndustryHubIdIndexRoute: IndustryHubsIndustryHubIdIndexRoute,
  }

const IndustryHubsIndustryHubIdRouteRouteWithChildren =
  IndustryHubsIndustryHubIdRouteRoute._addFileChildren(
    IndustryHubsIndustryHubIdRouteRouteChildren,
  )

interface StructuresStructureIdRouteRouteChildren {
  StructuresStructureIdIndexRoute: typeof StructuresStructureIdIndexRoute
}

const StructuresStructureIdRouteRouteChildren: StructuresStructureIdRouteRouteChildren =
  {
    StructuresStructureIdIndexRoute: StructuresStructureIdIndexRoute,
  }

const StructuresStructureIdRouteRouteWithChildren =
  StructuresStructureIdRouteRoute._addFileChildren(
    StructuresStructureIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndustryHubsRouteRoute: IndustryHubsRouteRouteWithChildren,
  StructuresRouteRoute: StructuresRouteRouteWithChildren,
  IndustryHubsIndustryHubIdRouteRoute:
    IndustryHubsIndustryHubIdRouteRouteWithChildren,
  StructuresStructureIdRouteRoute: StructuresStructureIdRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AboutIndexRoute: AboutIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
