/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuresRouteRouteImport } from './routes/structures/route'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as ProjectGroupsRouteRouteImport } from './routes/project-groups/route'
import { Route as IndustryHubsRouteRouteImport } from './routes/industry-hubs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StructuresIndexRouteImport } from './routes/structures/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectGroupsIndexRouteImport } from './routes/project-groups/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as IndustryHubsIndexRouteImport } from './routes/industry-hubs/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as StructuresStructureIdRouteRouteImport } from './routes/structures_/$structureId.route'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects_/$projectId.route'
import { Route as ProjectsAssistantRouteRouteImport } from './routes/projects/assistant/route'
import { Route as ProjectGroupsProjectGroupIdRouteRouteImport } from './routes/project-groups_/$projectGroupId.route'
import { Route as IndustryHubsIndustryHubIdRouteRouteImport } from './routes/industry-hubs_/$industryHubId.route'
import { Route as StructuresStructureIdIndexRouteImport } from './routes/structures_/$structureId.index'
import { Route as ProjectsAssistantIndexRouteImport } from './routes/projects/assistant/index'
import { Route as IndustryHubsIndustryHubIdIndexRouteImport } from './routes/industry-hubs_/$industryHubId.index'
import { Route as ProjectsProjectIdOverviewRouteImport } from './routes/projects_/$projectId.overview'
import { Route as ProjectsProjectIdMiscRouteImport } from './routes/projects_/$projectId.misc'
import { Route as ProjectsProjectIdMarketRouteImport } from './routes/projects_/$projectId.market'
import { Route as ProjectGroupsProjectGroupIdProjectsRouteImport } from './routes/project-groups_/$projectGroupId.projects'
import { Route as ProjectGroupsProjectGroupIdOverviewRouteImport } from './routes/project-groups_/$projectGroupId.overview'
import { Route as ProjectGroupsProjectGroupIdMembersRouteImport } from './routes/project-groups_/$projectGroupId.members'
import { Route as ProjectGroupsProjectGroupIdIndustryHubsRouteImport } from './routes/project-groups_/$projectGroupId.industry-hubs'
import { Route as ProjectGroupsProjectGroupIdDefaultsRouteImport } from './routes/project-groups_/$projectGroupId.defaults'

const StructuresRouteRoute = StructuresRouteRouteImport.update({
  id: '/structures',
  path: '/structures',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGroupsRouteRoute = ProjectGroupsRouteRouteImport.update({
  id: '/project-groups',
  path: '/project-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHubsRouteRoute = IndustryHubsRouteRouteImport.update({
  id: '/industry-hubs',
  path: '/industry-hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresIndexRoute = StructuresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StructuresRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectGroupsIndexRoute = ProjectGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectGroupsRouteRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHubsIndexRoute = IndustryHubsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustryHubsRouteRoute,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresStructureIdRouteRoute =
  StructuresStructureIdRouteRouteImport.update({
    id: '/structures_/$structureId',
    path: '/structures/$structureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAssistantRouteRoute = ProjectsAssistantRouteRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectGroupsProjectGroupIdRouteRoute =
  ProjectGroupsProjectGroupIdRouteRouteImport.update({
    id: '/project-groups_/$projectGroupId',
    path: '/project-groups/$projectGroupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryHubsIndustryHubIdRouteRoute =
  IndustryHubsIndustryHubIdRouteRouteImport.update({
    id: '/industry-hubs_/$industryHubId',
    path: '/industry-hubs/$industryHubId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StructuresStructureIdIndexRoute =
  StructuresStructureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StructuresStructureIdRouteRoute,
  } as any)
const ProjectsAssistantIndexRoute = ProjectsAssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsAssistantRouteRoute,
} as any)
const IndustryHubsIndustryHubIdIndexRoute =
  IndustryHubsIndustryHubIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IndustryHubsIndustryHubIdRouteRoute,
  } as any)
const ProjectsProjectIdOverviewRoute =
  ProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdMiscRoute = ProjectsProjectIdMiscRouteImport.update({
  id: '/misc',
  path: '/misc',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdMarketRoute = ProjectsProjectIdMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectGroupsProjectGroupIdProjectsRoute =
  ProjectGroupsProjectGroupIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdOverviewRoute =
  ProjectGroupsProjectGroupIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdMembersRoute =
  ProjectGroupsProjectGroupIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdIndustryHubsRoute =
  ProjectGroupsProjectGroupIdIndustryHubsRouteImport.update({
    id: '/industry-hubs',
    path: '/industry-hubs',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdDefaultsRoute =
  ProjectGroupsProjectGroupIdDefaultsRouteImport.update({
    id: '/defaults',
    path: '/defaults',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/industry-hubs': typeof IndustryHubsRouteRouteWithChildren
  '/project-groups': typeof ProjectGroupsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/industry-hubs/$industryHubId': typeof IndustryHubsIndustryHubIdRouteRouteWithChildren
  '/project-groups/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/projects/assistant': typeof ProjectsAssistantRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/structures/$structureId': typeof StructuresStructureIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AboutIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/industry-hubs/': typeof IndustryHubsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/project-groups/': typeof ProjectGroupsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/project-groups/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups/$projectGroupId/industry-hubs': typeof ProjectGroupsProjectGroupIdIndustryHubsRoute
  '/project-groups/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups/$projectGroupId/overview': typeof ProjectGroupsProjectGroupIdOverviewRoute
  '/project-groups/$projectGroupId/projects': typeof ProjectGroupsProjectGroupIdProjectsRoute
  '/projects/$projectId/market': typeof ProjectsProjectIdMarketRoute
  '/projects/$projectId/misc': typeof ProjectsProjectIdMiscRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/industry-hubs/$industryHubId/': typeof IndustryHubsIndustryHubIdIndexRoute
  '/projects/assistant/': typeof ProjectsAssistantIndexRoute
  '/structures/$structureId/': typeof StructuresStructureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project-groups/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AboutIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/industry-hubs': typeof IndustryHubsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/project-groups': typeof ProjectGroupsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/structures': typeof StructuresIndexRoute
  '/project-groups/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups/$projectGroupId/industry-hubs': typeof ProjectGroupsProjectGroupIdIndustryHubsRoute
  '/project-groups/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups/$projectGroupId/overview': typeof ProjectGroupsProjectGroupIdOverviewRoute
  '/project-groups/$projectGroupId/projects': typeof ProjectGroupsProjectGroupIdProjectsRoute
  '/projects/$projectId/market': typeof ProjectsProjectIdMarketRoute
  '/projects/$projectId/misc': typeof ProjectsProjectIdMiscRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/industry-hubs/$industryHubId': typeof IndustryHubsIndustryHubIdIndexRoute
  '/projects/assistant': typeof ProjectsAssistantIndexRoute
  '/structures/$structureId': typeof StructuresStructureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/industry-hubs': typeof IndustryHubsRouteRouteWithChildren
  '/project-groups': typeof ProjectGroupsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/industry-hubs_/$industryHubId': typeof IndustryHubsIndustryHubIdRouteRouteWithChildren
  '/project-groups_/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/projects/assistant': typeof ProjectsAssistantRouteRouteWithChildren
  '/projects_/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/structures_/$structureId': typeof StructuresStructureIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about/': typeof AboutIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/industry-hubs/': typeof IndustryHubsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/project-groups/': typeof ProjectGroupsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/project-groups_/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups_/$projectGroupId/industry-hubs': typeof ProjectGroupsProjectGroupIdIndustryHubsRoute
  '/project-groups_/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups_/$projectGroupId/overview': typeof ProjectGroupsProjectGroupIdOverviewRoute
  '/project-groups_/$projectGroupId/projects': typeof ProjectGroupsProjectGroupIdProjectsRoute
  '/projects_/$projectId/market': typeof ProjectsProjectIdMarketRoute
  '/projects_/$projectId/misc': typeof ProjectsProjectIdMiscRoute
  '/projects_/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/industry-hubs_/$industryHubId/': typeof IndustryHubsIndustryHubIdIndexRoute
  '/projects/assistant/': typeof ProjectsAssistantIndexRoute
  '/structures_/$structureId/': typeof StructuresStructureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/industry-hubs'
    | '/project-groups'
    | '/projects'
    | '/structures'
    | '/industry-hubs/$industryHubId'
    | '/project-groups/$projectGroupId'
    | '/projects/assistant'
    | '/projects/$projectId'
    | '/structures/$structureId'
    | '/auth/login'
    | '/about'
    | '/characters'
    | '/industry-hubs/'
    | '/legal'
    | '/project-groups/'
    | '/projects/'
    | '/structures/'
    | '/project-groups/$projectGroupId/defaults'
    | '/project-groups/$projectGroupId/industry-hubs'
    | '/project-groups/$projectGroupId/members'
    | '/project-groups/$projectGroupId/overview'
    | '/project-groups/$projectGroupId/projects'
    | '/projects/$projectId/market'
    | '/projects/$projectId/misc'
    | '/projects/$projectId/overview'
    | '/industry-hubs/$industryHubId/'
    | '/projects/assistant/'
    | '/structures/$structureId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project-groups/$projectGroupId'
    | '/projects/$projectId'
    | '/auth/login'
    | '/about'
    | '/characters'
    | '/industry-hubs'
    | '/legal'
    | '/project-groups'
    | '/projects'
    | '/structures'
    | '/project-groups/$projectGroupId/defaults'
    | '/project-groups/$projectGroupId/industry-hubs'
    | '/project-groups/$projectGroupId/members'
    | '/project-groups/$projectGroupId/overview'
    | '/project-groups/$projectGroupId/projects'
    | '/projects/$projectId/market'
    | '/projects/$projectId/misc'
    | '/projects/$projectId/overview'
    | '/industry-hubs/$industryHubId'
    | '/projects/assistant'
    | '/structures/$structureId'
  id:
    | '__root__'
    | '/'
    | '/industry-hubs'
    | '/project-groups'
    | '/projects'
    | '/structures'
    | '/industry-hubs_/$industryHubId'
    | '/project-groups_/$projectGroupId'
    | '/projects/assistant'
    | '/projects_/$projectId'
    | '/structures_/$structureId'
    | '/auth/login'
    | '/about/'
    | '/characters/'
    | '/industry-hubs/'
    | '/legal/'
    | '/project-groups/'
    | '/projects/'
    | '/structures/'
    | '/project-groups_/$projectGroupId/defaults'
    | '/project-groups_/$projectGroupId/industry-hubs'
    | '/project-groups_/$projectGroupId/members'
    | '/project-groups_/$projectGroupId/overview'
    | '/project-groups_/$projectGroupId/projects'
    | '/projects_/$projectId/market'
    | '/projects_/$projectId/misc'
    | '/projects_/$projectId/overview'
    | '/industry-hubs_/$industryHubId/'
    | '/projects/assistant/'
    | '/structures_/$structureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndustryHubsRouteRoute: typeof IndustryHubsRouteRouteWithChildren
  ProjectGroupsRouteRoute: typeof ProjectGroupsRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  StructuresRouteRoute: typeof StructuresRouteRouteWithChildren
  IndustryHubsIndustryHubIdRouteRoute: typeof IndustryHubsIndustryHubIdRouteRouteWithChildren
  ProjectGroupsProjectGroupIdRouteRoute: typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  StructuresStructureIdRouteRoute: typeof StructuresStructureIdRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structures': {
      id: '/structures'
      path: '/structures'
      fullPath: '/structures'
      preLoaderRoute: typeof StructuresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-groups': {
      id: '/project-groups'
      path: '/project-groups'
      fullPath: '/project-groups'
      preLoaderRoute: typeof ProjectGroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hubs': {
      id: '/industry-hubs'
      path: '/industry-hubs'
      fullPath: '/industry-hubs'
      preLoaderRoute: typeof IndustryHubsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures/': {
      id: '/structures/'
      path: '/'
      fullPath: '/structures/'
      preLoaderRoute: typeof StructuresIndexRouteImport
      parentRoute: typeof StructuresRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/project-groups/': {
      id: '/project-groups/'
      path: '/'
      fullPath: '/project-groups/'
      preLoaderRoute: typeof ProjectGroupsIndexRouteImport
      parentRoute: typeof ProjectGroupsRouteRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hubs/': {
      id: '/industry-hubs/'
      path: '/'
      fullPath: '/industry-hubs/'
      preLoaderRoute: typeof IndustryHubsIndexRouteImport
      parentRoute: typeof IndustryHubsRouteRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures_/$structureId': {
      id: '/structures_/$structureId'
      path: '/structures/$structureId'
      fullPath: '/structures/$structureId'
      preLoaderRoute: typeof StructuresStructureIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/assistant': {
      id: '/projects/assistant'
      path: '/assistant'
      fullPath: '/projects/assistant'
      preLoaderRoute: typeof ProjectsAssistantRouteRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/project-groups_/$projectGroupId': {
      id: '/project-groups_/$projectGroupId'
      path: '/project-groups/$projectGroupId'
      fullPath: '/project-groups/$projectGroupId'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hubs_/$industryHubId': {
      id: '/industry-hubs_/$industryHubId'
      path: '/industry-hubs/$industryHubId'
      fullPath: '/industry-hubs/$industryHubId'
      preLoaderRoute: typeof IndustryHubsIndustryHubIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures_/$structureId/': {
      id: '/structures_/$structureId/'
      path: '/'
      fullPath: '/structures/$structureId/'
      preLoaderRoute: typeof StructuresStructureIdIndexRouteImport
      parentRoute: typeof StructuresStructureIdRouteRoute
    }
    '/projects/assistant/': {
      id: '/projects/assistant/'
      path: '/'
      fullPath: '/projects/assistant/'
      preLoaderRoute: typeof ProjectsAssistantIndexRouteImport
      parentRoute: typeof ProjectsAssistantRouteRoute
    }
    '/industry-hubs_/$industryHubId/': {
      id: '/industry-hubs_/$industryHubId/'
      path: '/'
      fullPath: '/industry-hubs/$industryHubId/'
      preLoaderRoute: typeof IndustryHubsIndustryHubIdIndexRouteImport
      parentRoute: typeof IndustryHubsIndustryHubIdRouteRoute
    }
    '/projects_/$projectId/overview': {
      id: '/projects_/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof ProjectsProjectIdOverviewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects_/$projectId/misc': {
      id: '/projects_/$projectId/misc'
      path: '/misc'
      fullPath: '/projects/$projectId/misc'
      preLoaderRoute: typeof ProjectsProjectIdMiscRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects_/$projectId/market': {
      id: '/projects_/$projectId/market'
      path: '/market'
      fullPath: '/projects/$projectId/market'
      preLoaderRoute: typeof ProjectsProjectIdMarketRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/project-groups_/$projectGroupId/projects': {
      id: '/project-groups_/$projectGroupId/projects'
      path: '/projects'
      fullPath: '/project-groups/$projectGroupId/projects'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdProjectsRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/overview': {
      id: '/project-groups_/$projectGroupId/overview'
      path: '/overview'
      fullPath: '/project-groups/$projectGroupId/overview'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdOverviewRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/members': {
      id: '/project-groups_/$projectGroupId/members'
      path: '/members'
      fullPath: '/project-groups/$projectGroupId/members'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdMembersRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/industry-hubs': {
      id: '/project-groups_/$projectGroupId/industry-hubs'
      path: '/industry-hubs'
      fullPath: '/project-groups/$projectGroupId/industry-hubs'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdIndustryHubsRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/defaults': {
      id: '/project-groups_/$projectGroupId/defaults'
      path: '/defaults'
      fullPath: '/project-groups/$projectGroupId/defaults'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdDefaultsRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
  }
}

interface IndustryHubsRouteRouteChildren {
  IndustryHubsIndexRoute: typeof IndustryHubsIndexRoute
}

const IndustryHubsRouteRouteChildren: IndustryHubsRouteRouteChildren = {
  IndustryHubsIndexRoute: IndustryHubsIndexRoute,
}

const IndustryHubsRouteRouteWithChildren =
  IndustryHubsRouteRoute._addFileChildren(IndustryHubsRouteRouteChildren)

interface ProjectGroupsRouteRouteChildren {
  ProjectGroupsIndexRoute: typeof ProjectGroupsIndexRoute
}

const ProjectGroupsRouteRouteChildren: ProjectGroupsRouteRouteChildren = {
  ProjectGroupsIndexRoute: ProjectGroupsIndexRoute,
}

const ProjectGroupsRouteRouteWithChildren =
  ProjectGroupsRouteRoute._addFileChildren(ProjectGroupsRouteRouteChildren)

interface ProjectsAssistantRouteRouteChildren {
  ProjectsAssistantIndexRoute: typeof ProjectsAssistantIndexRoute
}

const ProjectsAssistantRouteRouteChildren: ProjectsAssistantRouteRouteChildren =
  {
    ProjectsAssistantIndexRoute: ProjectsAssistantIndexRoute,
  }

const ProjectsAssistantRouteRouteWithChildren =
  ProjectsAssistantRouteRoute._addFileChildren(
    ProjectsAssistantRouteRouteChildren,
  )

interface ProjectsRouteRouteChildren {
  ProjectsAssistantRouteRoute: typeof ProjectsAssistantRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsAssistantRouteRoute: ProjectsAssistantRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface StructuresRouteRouteChildren {
  StructuresIndexRoute: typeof StructuresIndexRoute
}

const StructuresRouteRouteChildren: StructuresRouteRouteChildren = {
  StructuresIndexRoute: StructuresIndexRoute,
}

const StructuresRouteRouteWithChildren = StructuresRouteRoute._addFileChildren(
  StructuresRouteRouteChildren,
)

interface IndustryHubsIndustryHubIdRouteRouteChildren {
  IndustryHubsIndustryHubIdIndexRoute: typeof IndustryHubsIndustryHubIdIndexRoute
}

const IndustryHubsIndustryHubIdRouteRouteChildren: IndustryHubsIndustryHubIdRouteRouteChildren =
  {
    IndustryHubsIndustryHubIdIndexRoute: IndustryHubsIndustryHubIdIndexRoute,
  }

const IndustryHubsIndustryHubIdRouteRouteWithChildren =
  IndustryHubsIndustryHubIdRouteRoute._addFileChildren(
    IndustryHubsIndustryHubIdRouteRouteChildren,
  )

interface ProjectGroupsProjectGroupIdRouteRouteChildren {
  ProjectGroupsProjectGroupIdDefaultsRoute: typeof ProjectGroupsProjectGroupIdDefaultsRoute
  ProjectGroupsProjectGroupIdIndustryHubsRoute: typeof ProjectGroupsProjectGroupIdIndustryHubsRoute
  ProjectGroupsProjectGroupIdMembersRoute: typeof ProjectGroupsProjectGroupIdMembersRoute
  ProjectGroupsProjectGroupIdOverviewRoute: typeof ProjectGroupsProjectGroupIdOverviewRoute
  ProjectGroupsProjectGroupIdProjectsRoute: typeof ProjectGroupsProjectGroupIdProjectsRoute
}

const ProjectGroupsProjectGroupIdRouteRouteChildren: ProjectGroupsProjectGroupIdRouteRouteChildren =
  {
    ProjectGroupsProjectGroupIdDefaultsRoute:
      ProjectGroupsProjectGroupIdDefaultsRoute,
    ProjectGroupsProjectGroupIdIndustryHubsRoute:
      ProjectGroupsProjectGroupIdIndustryHubsRoute,
    ProjectGroupsProjectGroupIdMembersRoute:
      ProjectGroupsProjectGroupIdMembersRoute,
    ProjectGroupsProjectGroupIdOverviewRoute:
      ProjectGroupsProjectGroupIdOverviewRoute,
    ProjectGroupsProjectGroupIdProjectsRoute:
      ProjectGroupsProjectGroupIdProjectsRoute,
  }

const ProjectGroupsProjectGroupIdRouteRouteWithChildren =
  ProjectGroupsProjectGroupIdRouteRoute._addFileChildren(
    ProjectGroupsProjectGroupIdRouteRouteChildren,
  )

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdMarketRoute: typeof ProjectsProjectIdMarketRoute
  ProjectsProjectIdMiscRoute: typeof ProjectsProjectIdMiscRoute
  ProjectsProjectIdOverviewRoute: typeof ProjectsProjectIdOverviewRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdMarketRoute: ProjectsProjectIdMarketRoute,
    ProjectsProjectIdMiscRoute: ProjectsProjectIdMiscRoute,
    ProjectsProjectIdOverviewRoute: ProjectsProjectIdOverviewRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

interface StructuresStructureIdRouteRouteChildren {
  StructuresStructureIdIndexRoute: typeof StructuresStructureIdIndexRoute
}

const StructuresStructureIdRouteRouteChildren: StructuresStructureIdRouteRouteChildren =
  {
    StructuresStructureIdIndexRoute: StructuresStructureIdIndexRoute,
  }

const StructuresStructureIdRouteRouteWithChildren =
  StructuresStructureIdRouteRoute._addFileChildren(
    StructuresStructureIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndustryHubsRouteRoute: IndustryHubsRouteRouteWithChildren,
  ProjectGroupsRouteRoute: ProjectGroupsRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  StructuresRouteRoute: StructuresRouteRouteWithChildren,
  IndustryHubsIndustryHubIdRouteRoute:
    IndustryHubsIndustryHubIdRouteRouteWithChildren,
  ProjectGroupsProjectGroupIdRouteRoute:
    ProjectGroupsProjectGroupIdRouteRouteWithChildren,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  StructuresStructureIdRouteRoute: StructuresStructureIdRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AboutIndexRoute: AboutIndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
