/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AppraisalsIndexRouteImport } from './routes/appraisals/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as AppraisalsCodeIndexRouteImport } from './routes/appraisals_/$code.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsIndexRoute = AppraisalsIndexRouteImport.update({
  id: '/appraisals/',
  path: '/appraisals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsCodeIndexRoute = AppraisalsCodeIndexRouteImport.update({
  id: '/appraisals_/$code/',
  path: '/appraisals/$code/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/about/': typeof AboutIndexRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/appraisals/$code/': typeof AppraisalsCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AboutIndexRoute
  '/appraisals': typeof AppraisalsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/appraisals/$code': typeof AppraisalsCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/about/': typeof AboutIndexRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/appraisals_/$code/': typeof AppraisalsCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/about/'
    | '/appraisals/'
    | '/legal/'
    | '/appraisals/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/about'
    | '/appraisals'
    | '/legal'
    | '/appraisals/$code'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/about/'
    | '/appraisals/'
    | '/legal/'
    | '/appraisals_/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AppraisalsIndexRoute: typeof AppraisalsIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  AppraisalsCodeIndexRoute: typeof AppraisalsCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/': {
      id: '/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals/'
      preLoaderRoute: typeof AppraisalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals_/$code/': {
      id: '/appraisals_/$code/'
      path: '/appraisals/$code'
      fullPath: '/appraisals/$code/'
      preLoaderRoute: typeof AppraisalsCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AboutIndexRoute: AboutIndexRoute,
  AppraisalsIndexRoute: AppraisalsIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  AppraisalsCodeIndexRoute: AppraisalsCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
