ALTER TABLE structure ADD COLUMN IF NOT EXISTS x REAL NOT NULL DEFAULT 0;
ALTER TABLE structure ADD COLUMN IF NOT EXISTS y REAL NOT NULL DEFAULT 0;
ALTER TABLE structure ADD COLUMN IF NOT EXISTS z REAL NOT NULL DEFAULT 0;

ALTER TABLE structure ALTER COLUMN x DROP DEFAULT;
ALTER TABLE structure ALTER COLUMN y DROP DEFAULT;
ALTER TABLE structure ALTER COLUMN z DROP DEFAULT;
