CREATE TABLE IF NOT EXISTS system_distance (
    system_start    INTEGER             NOT NULL,
    system_end      INTEGER             NOT NULL,
    distance_ly     DOUBLE PRECISION    NOT NULL,

    PRIMARY KEY(system_start, system_end)
);

ALTER TABLE system ADD COLUMN IF NOT EXISTS x DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE system ADD COLUMN IF NOT EXISTS y DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE system ADD COLUMN IF NOT EXISTS z DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE system ALTER COLUMN x DROP DEFAULT;
ALTER TABLE system ALTER COLUMN y DROP DEFAULT;
ALTER TABLE system ALTER COLUMN z DROP DEFAULT;
