ALTER TABLE structure_rig ADD COLUMN excludes INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE system ADD COLUMN security_str VARCHAR NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE system ALTER COLUMN security_str DROP DEFAULT;
