ALTER TABLE structure_rig ADD COLUMN IF NOT EXISTS excludes INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE system ADD COLUMN IF NOT EXISTS security_str VARCHAR NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE system ALTER COLUMN security_str DROP DEFAULT;
