/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuresRouteRouteImport } from './routes/structures/route'
import { Route as ProjectGroupsRouteRouteImport } from './routes/project-groups/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StructuresIndexRouteImport } from './routes/structures/index'
import { Route as ProjectGroupsIndexRouteImport } from './routes/project-groups/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as StructuresAddRouteImport } from './routes/structures/add'
import { Route as ProjectGroupsCreateRouteImport } from './routes/project-groups/create'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProjectGroupsProjectGroupIdRouteRouteImport } from './routes/project-groups_/$projectGroupId.route'
import { Route as ProjectGroupsProjectGroupIdIndexRouteImport } from './routes/project-groups_/$projectGroupId.index'
import { Route as ProjectGroupsProjectGroupIdMembersRouteImport } from './routes/project-groups_/$projectGroupId.members'
import { Route as ProjectGroupsProjectGroupIdDefaultsRouteImport } from './routes/project-groups_/$projectGroupId.defaults'

const StructuresRouteRoute = StructuresRouteRouteImport.update({
  id: '/structures',
  path: '/structures',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGroupsRouteRoute = ProjectGroupsRouteRouteImport.update({
  id: '/project-groups',
  path: '/project-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresIndexRoute = StructuresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StructuresRouteRoute,
} as any)
const ProjectGroupsIndexRoute = ProjectGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectGroupsRouteRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresAddRoute = StructuresAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => StructuresRouteRoute,
} as any)
const ProjectGroupsCreateRoute = ProjectGroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProjectGroupsRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGroupsProjectGroupIdRouteRoute =
  ProjectGroupsProjectGroupIdRouteRouteImport.update({
    id: '/project-groups_/$projectGroupId',
    path: '/project-groups/$projectGroupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectGroupsProjectGroupIdIndexRoute =
  ProjectGroupsProjectGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdMembersRoute =
  ProjectGroupsProjectGroupIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdDefaultsRoute =
  ProjectGroupsProjectGroupIdDefaultsRouteImport.update({
    id: '/defaults',
    path: '/defaults',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project-groups': typeof ProjectGroupsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/project-groups/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/project-groups/create': typeof ProjectGroupsCreateRoute
  '/structures/add': typeof StructuresAddRoute
  '/about': typeof AboutIndexRoute
  '/legal': typeof LegalIndexRoute
  '/project-groups/': typeof ProjectGroupsIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/project-groups/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups/$projectGroupId/': typeof ProjectGroupsProjectGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/project-groups/create': typeof ProjectGroupsCreateRoute
  '/structures/add': typeof StructuresAddRoute
  '/about': typeof AboutIndexRoute
  '/legal': typeof LegalIndexRoute
  '/project-groups': typeof ProjectGroupsIndexRoute
  '/structures': typeof StructuresIndexRoute
  '/project-groups/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups/$projectGroupId': typeof ProjectGroupsProjectGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project-groups': typeof ProjectGroupsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/project-groups_/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/project-groups/create': typeof ProjectGroupsCreateRoute
  '/structures/add': typeof StructuresAddRoute
  '/about/': typeof AboutIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/project-groups/': typeof ProjectGroupsIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/project-groups_/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups_/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups_/$projectGroupId/': typeof ProjectGroupsProjectGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project-groups'
    | '/structures'
    | '/project-groups/$projectGroupId'
    | '/auth/login'
    | '/project-groups/create'
    | '/structures/add'
    | '/about'
    | '/legal'
    | '/project-groups/'
    | '/structures/'
    | '/project-groups/$projectGroupId/defaults'
    | '/project-groups/$projectGroupId/members'
    | '/project-groups/$projectGroupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/project-groups/create'
    | '/structures/add'
    | '/about'
    | '/legal'
    | '/project-groups'
    | '/structures'
    | '/project-groups/$projectGroupId/defaults'
    | '/project-groups/$projectGroupId/members'
    | '/project-groups/$projectGroupId'
  id:
    | '__root__'
    | '/'
    | '/project-groups'
    | '/structures'
    | '/project-groups_/$projectGroupId'
    | '/auth/login'
    | '/project-groups/create'
    | '/structures/add'
    | '/about/'
    | '/legal/'
    | '/project-groups/'
    | '/structures/'
    | '/project-groups_/$projectGroupId/defaults'
    | '/project-groups_/$projectGroupId/members'
    | '/project-groups_/$projectGroupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectGroupsRouteRoute: typeof ProjectGroupsRouteRouteWithChildren
  StructuresRouteRoute: typeof StructuresRouteRouteWithChildren
  ProjectGroupsProjectGroupIdRouteRoute: typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AboutIndexRoute: typeof AboutIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structures': {
      id: '/structures'
      path: '/structures'
      fullPath: '/structures'
      preLoaderRoute: typeof StructuresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-groups': {
      id: '/project-groups'
      path: '/project-groups'
      fullPath: '/project-groups'
      preLoaderRoute: typeof ProjectGroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures/': {
      id: '/structures/'
      path: '/'
      fullPath: '/structures/'
      preLoaderRoute: typeof StructuresIndexRouteImport
      parentRoute: typeof StructuresRouteRoute
    }
    '/project-groups/': {
      id: '/project-groups/'
      path: '/'
      fullPath: '/project-groups/'
      preLoaderRoute: typeof ProjectGroupsIndexRouteImport
      parentRoute: typeof ProjectGroupsRouteRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures/add': {
      id: '/structures/add'
      path: '/add'
      fullPath: '/structures/add'
      preLoaderRoute: typeof StructuresAddRouteImport
      parentRoute: typeof StructuresRouteRoute
    }
    '/project-groups/create': {
      id: '/project-groups/create'
      path: '/create'
      fullPath: '/project-groups/create'
      preLoaderRoute: typeof ProjectGroupsCreateRouteImport
      parentRoute: typeof ProjectGroupsRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-groups_/$projectGroupId': {
      id: '/project-groups_/$projectGroupId'
      path: '/project-groups/$projectGroupId'
      fullPath: '/project-groups/$projectGroupId'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-groups_/$projectGroupId/': {
      id: '/project-groups_/$projectGroupId/'
      path: '/'
      fullPath: '/project-groups/$projectGroupId/'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdIndexRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/members': {
      id: '/project-groups_/$projectGroupId/members'
      path: '/members'
      fullPath: '/project-groups/$projectGroupId/members'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdMembersRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/defaults': {
      id: '/project-groups_/$projectGroupId/defaults'
      path: '/defaults'
      fullPath: '/project-groups/$projectGroupId/defaults'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdDefaultsRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
  }
}

interface ProjectGroupsRouteRouteChildren {
  ProjectGroupsCreateRoute: typeof ProjectGroupsCreateRoute
  ProjectGroupsIndexRoute: typeof ProjectGroupsIndexRoute
}

const ProjectGroupsRouteRouteChildren: ProjectGroupsRouteRouteChildren = {
  ProjectGroupsCreateRoute: ProjectGroupsCreateRoute,
  ProjectGroupsIndexRoute: ProjectGroupsIndexRoute,
}

const ProjectGroupsRouteRouteWithChildren =
  ProjectGroupsRouteRoute._addFileChildren(ProjectGroupsRouteRouteChildren)

interface StructuresRouteRouteChildren {
  StructuresAddRoute: typeof StructuresAddRoute
  StructuresIndexRoute: typeof StructuresIndexRoute
}

const StructuresRouteRouteChildren: StructuresRouteRouteChildren = {
  StructuresAddRoute: StructuresAddRoute,
  StructuresIndexRoute: StructuresIndexRoute,
}

const StructuresRouteRouteWithChildren = StructuresRouteRoute._addFileChildren(
  StructuresRouteRouteChildren,
)

interface ProjectGroupsProjectGroupIdRouteRouteChildren {
  ProjectGroupsProjectGroupIdDefaultsRoute: typeof ProjectGroupsProjectGroupIdDefaultsRoute
  ProjectGroupsProjectGroupIdMembersRoute: typeof ProjectGroupsProjectGroupIdMembersRoute
  ProjectGroupsProjectGroupIdIndexRoute: typeof ProjectGroupsProjectGroupIdIndexRoute
}

const ProjectGroupsProjectGroupIdRouteRouteChildren: ProjectGroupsProjectGroupIdRouteRouteChildren =
  {
    ProjectGroupsProjectGroupIdDefaultsRoute:
      ProjectGroupsProjectGroupIdDefaultsRoute,
    ProjectGroupsProjectGroupIdMembersRoute:
      ProjectGroupsProjectGroupIdMembersRoute,
    ProjectGroupsProjectGroupIdIndexRoute:
      ProjectGroupsProjectGroupIdIndexRoute,
  }

const ProjectGroupsProjectGroupIdRouteRouteWithChildren =
  ProjectGroupsProjectGroupIdRouteRoute._addFileChildren(
    ProjectGroupsProjectGroupIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectGroupsRouteRoute: ProjectGroupsRouteRouteWithChildren,
  StructuresRouteRoute: StructuresRouteRouteWithChildren,
  ProjectGroupsProjectGroupIdRouteRoute:
    ProjectGroupsProjectGroupIdRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AboutIndexRoute: AboutIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
