/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuresRouteRouteImport } from './routes/structures/route'
import { Route as StructureGroupsRouteRouteImport } from './routes/structure-groups/route'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as ProjectGroupsRouteRouteImport } from './routes/project-groups/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StructuresIndexRouteImport } from './routes/structures/index'
import { Route as StructureGroupsIndexRouteImport } from './routes/structure-groups/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectGroupsIndexRouteImport } from './routes/project-groups/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as StructuresStructureIdRouteRouteImport } from './routes/structures_/$structureId.route'
import { Route as StructureGroupsStructureGroupIdRouteRouteImport } from './routes/structure-groups_/$structureGroupId.route'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects_/$projectId.route'
import { Route as ProjectGroupsProjectGroupIdRouteRouteImport } from './routes/project-groups_/$projectGroupId.route'
import { Route as StructuresStructureIdIndexRouteImport } from './routes/structures_/$structureId.index'
import { Route as StructureGroupsStructureGroupIdIndexRouteImport } from './routes/structure-groups_/$structureGroupId.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects_/$projectId.index'
import { Route as ProjectGroupsProjectGroupIdOverviewRouteImport } from './routes/project-groups_/$projectGroupId.overview'
import { Route as ProjectGroupsProjectGroupIdMembersRouteImport } from './routes/project-groups_/$projectGroupId.members'
import { Route as ProjectGroupsProjectGroupIdDefaultsRouteImport } from './routes/project-groups_/$projectGroupId.defaults'

const StructuresRouteRoute = StructuresRouteRouteImport.update({
  id: '/structures',
  path: '/structures',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureGroupsRouteRoute = StructureGroupsRouteRouteImport.update({
  id: '/structure-groups',
  path: '/structure-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGroupsRouteRoute = ProjectGroupsRouteRouteImport.update({
  id: '/project-groups',
  path: '/project-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresIndexRoute = StructuresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StructuresRouteRoute,
} as any)
const StructureGroupsIndexRoute = StructureGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StructureGroupsRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectGroupsIndexRoute = ProjectGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectGroupsRouteRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuresStructureIdRouteRoute =
  StructuresStructureIdRouteRouteImport.update({
    id: '/structures_/$structureId',
    path: '/structures/$structureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StructureGroupsStructureGroupIdRouteRoute =
  StructureGroupsStructureGroupIdRouteRouteImport.update({
    id: '/structure-groups_/$structureGroupId',
    path: '/structure-groups/$structureGroupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGroupsProjectGroupIdRouteRoute =
  ProjectGroupsProjectGroupIdRouteRouteImport.update({
    id: '/project-groups_/$projectGroupId',
    path: '/project-groups/$projectGroupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StructuresStructureIdIndexRoute =
  StructuresStructureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StructuresStructureIdRouteRoute,
  } as any)
const StructureGroupsStructureGroupIdIndexRoute =
  StructureGroupsStructureGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StructureGroupsStructureGroupIdRouteRoute,
  } as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectGroupsProjectGroupIdOverviewRoute =
  ProjectGroupsProjectGroupIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdMembersRoute =
  ProjectGroupsProjectGroupIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)
const ProjectGroupsProjectGroupIdDefaultsRoute =
  ProjectGroupsProjectGroupIdDefaultsRouteImport.update({
    id: '/defaults',
    path: '/defaults',
    getParentRoute: () => ProjectGroupsProjectGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project-groups': typeof ProjectGroupsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/structure-groups': typeof StructureGroupsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/project-groups/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/structure-groups/$structureGroupId': typeof StructureGroupsStructureGroupIdRouteRouteWithChildren
  '/structures/$structureId': typeof StructuresStructureIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AboutIndexRoute
  '/legal': typeof LegalIndexRoute
  '/project-groups/': typeof ProjectGroupsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/structure-groups/': typeof StructureGroupsIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/project-groups/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups/$projectGroupId/overview': typeof ProjectGroupsProjectGroupIdOverviewRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/structure-groups/$structureGroupId/': typeof StructureGroupsStructureGroupIdIndexRoute
  '/structures/$structureId/': typeof StructuresStructureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project-groups/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AboutIndexRoute
  '/legal': typeof LegalIndexRoute
  '/project-groups': typeof ProjectGroupsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/structure-groups': typeof StructureGroupsIndexRoute
  '/structures': typeof StructuresIndexRoute
  '/project-groups/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups/$projectGroupId/overview': typeof ProjectGroupsProjectGroupIdOverviewRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/structure-groups/$structureGroupId': typeof StructureGroupsStructureGroupIdIndexRoute
  '/structures/$structureId': typeof StructuresStructureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project-groups': typeof ProjectGroupsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/structure-groups': typeof StructureGroupsRouteRouteWithChildren
  '/structures': typeof StructuresRouteRouteWithChildren
  '/project-groups_/$projectGroupId': typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  '/projects_/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/structure-groups_/$structureGroupId': typeof StructureGroupsStructureGroupIdRouteRouteWithChildren
  '/structures_/$structureId': typeof StructuresStructureIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/about/': typeof AboutIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/project-groups/': typeof ProjectGroupsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/structure-groups/': typeof StructureGroupsIndexRoute
  '/structures/': typeof StructuresIndexRoute
  '/project-groups_/$projectGroupId/defaults': typeof ProjectGroupsProjectGroupIdDefaultsRoute
  '/project-groups_/$projectGroupId/members': typeof ProjectGroupsProjectGroupIdMembersRoute
  '/project-groups_/$projectGroupId/overview': typeof ProjectGroupsProjectGroupIdOverviewRoute
  '/projects_/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/structure-groups_/$structureGroupId/': typeof StructureGroupsStructureGroupIdIndexRoute
  '/structures_/$structureId/': typeof StructuresStructureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project-groups'
    | '/projects'
    | '/structure-groups'
    | '/structures'
    | '/project-groups/$projectGroupId'
    | '/projects/$projectId'
    | '/structure-groups/$structureGroupId'
    | '/structures/$structureId'
    | '/auth/login'
    | '/about'
    | '/legal'
    | '/project-groups/'
    | '/projects/'
    | '/structure-groups/'
    | '/structures/'
    | '/project-groups/$projectGroupId/defaults'
    | '/project-groups/$projectGroupId/members'
    | '/project-groups/$projectGroupId/overview'
    | '/projects/$projectId/'
    | '/structure-groups/$structureGroupId/'
    | '/structures/$structureId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project-groups/$projectGroupId'
    | '/auth/login'
    | '/about'
    | '/legal'
    | '/project-groups'
    | '/projects'
    | '/structure-groups'
    | '/structures'
    | '/project-groups/$projectGroupId/defaults'
    | '/project-groups/$projectGroupId/members'
    | '/project-groups/$projectGroupId/overview'
    | '/projects/$projectId'
    | '/structure-groups/$structureGroupId'
    | '/structures/$structureId'
  id:
    | '__root__'
    | '/'
    | '/project-groups'
    | '/projects'
    | '/structure-groups'
    | '/structures'
    | '/project-groups_/$projectGroupId'
    | '/projects_/$projectId'
    | '/structure-groups_/$structureGroupId'
    | '/structures_/$structureId'
    | '/auth/login'
    | '/about/'
    | '/legal/'
    | '/project-groups/'
    | '/projects/'
    | '/structure-groups/'
    | '/structures/'
    | '/project-groups_/$projectGroupId/defaults'
    | '/project-groups_/$projectGroupId/members'
    | '/project-groups_/$projectGroupId/overview'
    | '/projects_/$projectId/'
    | '/structure-groups_/$structureGroupId/'
    | '/structures_/$structureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectGroupsRouteRoute: typeof ProjectGroupsRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  StructureGroupsRouteRoute: typeof StructureGroupsRouteRouteWithChildren
  StructuresRouteRoute: typeof StructuresRouteRouteWithChildren
  ProjectGroupsProjectGroupIdRouteRoute: typeof ProjectGroupsProjectGroupIdRouteRouteWithChildren
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  StructureGroupsStructureGroupIdRouteRoute: typeof StructureGroupsStructureGroupIdRouteRouteWithChildren
  StructuresStructureIdRouteRoute: typeof StructuresStructureIdRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AboutIndexRoute: typeof AboutIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structures': {
      id: '/structures'
      path: '/structures'
      fullPath: '/structures'
      preLoaderRoute: typeof StructuresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure-groups': {
      id: '/structure-groups'
      path: '/structure-groups'
      fullPath: '/structure-groups'
      preLoaderRoute: typeof StructureGroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-groups': {
      id: '/project-groups'
      path: '/project-groups'
      fullPath: '/project-groups'
      preLoaderRoute: typeof ProjectGroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures/': {
      id: '/structures/'
      path: '/'
      fullPath: '/structures/'
      preLoaderRoute: typeof StructuresIndexRouteImport
      parentRoute: typeof StructuresRouteRoute
    }
    '/structure-groups/': {
      id: '/structure-groups/'
      path: '/'
      fullPath: '/structure-groups/'
      preLoaderRoute: typeof StructureGroupsIndexRouteImport
      parentRoute: typeof StructureGroupsRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/project-groups/': {
      id: '/project-groups/'
      path: '/'
      fullPath: '/project-groups/'
      preLoaderRoute: typeof ProjectGroupsIndexRouteImport
      parentRoute: typeof ProjectGroupsRouteRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures_/$structureId': {
      id: '/structures_/$structureId'
      path: '/structures/$structureId'
      fullPath: '/structures/$structureId'
      preLoaderRoute: typeof StructuresStructureIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure-groups_/$structureGroupId': {
      id: '/structure-groups_/$structureGroupId'
      path: '/structure-groups/$structureGroupId'
      fullPath: '/structure-groups/$structureGroupId'
      preLoaderRoute: typeof StructureGroupsStructureGroupIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-groups_/$projectGroupId': {
      id: '/project-groups_/$projectGroupId'
      path: '/project-groups/$projectGroupId'
      fullPath: '/project-groups/$projectGroupId'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structures_/$structureId/': {
      id: '/structures_/$structureId/'
      path: '/'
      fullPath: '/structures/$structureId/'
      preLoaderRoute: typeof StructuresStructureIdIndexRouteImport
      parentRoute: typeof StructuresStructureIdRouteRoute
    }
    '/structure-groups_/$structureGroupId/': {
      id: '/structure-groups_/$structureGroupId/'
      path: '/'
      fullPath: '/structure-groups/$structureGroupId/'
      preLoaderRoute: typeof StructureGroupsStructureGroupIdIndexRouteImport
      parentRoute: typeof StructureGroupsStructureGroupIdRouteRoute
    }
    '/projects_/$projectId/': {
      id: '/projects_/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/project-groups_/$projectGroupId/overview': {
      id: '/project-groups_/$projectGroupId/overview'
      path: '/overview'
      fullPath: '/project-groups/$projectGroupId/overview'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdOverviewRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/members': {
      id: '/project-groups_/$projectGroupId/members'
      path: '/members'
      fullPath: '/project-groups/$projectGroupId/members'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdMembersRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
    '/project-groups_/$projectGroupId/defaults': {
      id: '/project-groups_/$projectGroupId/defaults'
      path: '/defaults'
      fullPath: '/project-groups/$projectGroupId/defaults'
      preLoaderRoute: typeof ProjectGroupsProjectGroupIdDefaultsRouteImport
      parentRoute: typeof ProjectGroupsProjectGroupIdRouteRoute
    }
  }
}

interface ProjectGroupsRouteRouteChildren {
  ProjectGroupsIndexRoute: typeof ProjectGroupsIndexRoute
}

const ProjectGroupsRouteRouteChildren: ProjectGroupsRouteRouteChildren = {
  ProjectGroupsIndexRoute: ProjectGroupsIndexRoute,
}

const ProjectGroupsRouteRouteWithChildren =
  ProjectGroupsRouteRoute._addFileChildren(ProjectGroupsRouteRouteChildren)

interface ProjectsRouteRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface StructureGroupsRouteRouteChildren {
  StructureGroupsIndexRoute: typeof StructureGroupsIndexRoute
}

const StructureGroupsRouteRouteChildren: StructureGroupsRouteRouteChildren = {
  StructureGroupsIndexRoute: StructureGroupsIndexRoute,
}

const StructureGroupsRouteRouteWithChildren =
  StructureGroupsRouteRoute._addFileChildren(StructureGroupsRouteRouteChildren)

interface StructuresRouteRouteChildren {
  StructuresIndexRoute: typeof StructuresIndexRoute
}

const StructuresRouteRouteChildren: StructuresRouteRouteChildren = {
  StructuresIndexRoute: StructuresIndexRoute,
}

const StructuresRouteRouteWithChildren = StructuresRouteRoute._addFileChildren(
  StructuresRouteRouteChildren,
)

interface ProjectGroupsProjectGroupIdRouteRouteChildren {
  ProjectGroupsProjectGroupIdDefaultsRoute: typeof ProjectGroupsProjectGroupIdDefaultsRoute
  ProjectGroupsProjectGroupIdMembersRoute: typeof ProjectGroupsProjectGroupIdMembersRoute
  ProjectGroupsProjectGroupIdOverviewRoute: typeof ProjectGroupsProjectGroupIdOverviewRoute
}

const ProjectGroupsProjectGroupIdRouteRouteChildren: ProjectGroupsProjectGroupIdRouteRouteChildren =
  {
    ProjectGroupsProjectGroupIdDefaultsRoute:
      ProjectGroupsProjectGroupIdDefaultsRoute,
    ProjectGroupsProjectGroupIdMembersRoute:
      ProjectGroupsProjectGroupIdMembersRoute,
    ProjectGroupsProjectGroupIdOverviewRoute:
      ProjectGroupsProjectGroupIdOverviewRoute,
  }

const ProjectGroupsProjectGroupIdRouteRouteWithChildren =
  ProjectGroupsProjectGroupIdRouteRoute._addFileChildren(
    ProjectGroupsProjectGroupIdRouteRouteChildren,
  )

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

interface StructureGroupsStructureGroupIdRouteRouteChildren {
  StructureGroupsStructureGroupIdIndexRoute: typeof StructureGroupsStructureGroupIdIndexRoute
}

const StructureGroupsStructureGroupIdRouteRouteChildren: StructureGroupsStructureGroupIdRouteRouteChildren =
  {
    StructureGroupsStructureGroupIdIndexRoute:
      StructureGroupsStructureGroupIdIndexRoute,
  }

const StructureGroupsStructureGroupIdRouteRouteWithChildren =
  StructureGroupsStructureGroupIdRouteRoute._addFileChildren(
    StructureGroupsStructureGroupIdRouteRouteChildren,
  )

interface StructuresStructureIdRouteRouteChildren {
  StructuresStructureIdIndexRoute: typeof StructuresStructureIdIndexRoute
}

const StructuresStructureIdRouteRouteChildren: StructuresStructureIdRouteRouteChildren =
  {
    StructuresStructureIdIndexRoute: StructuresStructureIdIndexRoute,
  }

const StructuresStructureIdRouteRouteWithChildren =
  StructuresStructureIdRouteRoute._addFileChildren(
    StructuresStructureIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectGroupsRouteRoute: ProjectGroupsRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  StructureGroupsRouteRoute: StructureGroupsRouteRouteWithChildren,
  StructuresRouteRoute: StructuresRouteRouteWithChildren,
  ProjectGroupsProjectGroupIdRouteRoute:
    ProjectGroupsProjectGroupIdRouteRouteWithChildren,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  StructureGroupsStructureGroupIdRouteRoute:
    StructureGroupsStructureGroupIdRouteRouteWithChildren,
  StructuresStructureIdRouteRoute: StructuresStructureIdRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AboutIndexRoute: AboutIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
