on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1

jobs:
  check:
    name: check
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - name: Run cargo check
        run: cargo check

  test-backend:
    name: tests backend
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - name: Run cargo test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/starfoundry
        run: cargo test

  test-web:
    name: tests web
    runs-on: [self-hosted, linux]
    env:
      RUST_LOG: info,sqlx::query=error
      SECRET_KEY: NotASecret
      SERVER_ADDRESS: 0.0.0.0:10101
      DATABASE_URL: invalid
      EVE_USER_AGENT: github.com/chiefomnicron
      EVE_CALLBACK: invalod
      EVE_CLIENT_ID: invalid
      EVE_SECRET_KEY: invalid
      REDIRECT: invalid
      JANICE_USER_AGENT: github.com/chiefomnicron
      JANICE_API_KEY: invalid
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: cd webapp && npm install
      - name: Run browser tests
        run: make web-test
      - name: cleanup
        run: sudo rm -rf webapp/cypress webapp/node_modules

  release:
    name: release
    runs-on: [self-hosted, linux]
    needs: [check, test-backend, test-web]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build, tag, and push image to Amazon ECR
        env:
          SQLX_OFFLINE: true
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VITE_SENTRY: ${{ vars.VITE_SENTRY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          make docker-login
          make docker-build
          make docker-push
          echo ${{ github.sha }}

  trivy-repo:
    name: trivy repository
    runs-on: [self-hosted, linux]
    needs: [release]
    steps:
      - name: Checkout code 
        uses: actions/checkout@master
      - name: Run Trivy vulnerability scanner
        continue-on-error: true
        run: trivy fs . --parallel 0 --severity 'CRITICAL,HIGH'

  ship-it:
    name: Update references
    runs-on: [self-hosted, linux]
    needs: [release]
    steps:
      - name: Clone infra repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'ChiefOmnicron'
          repository: 'starfoundry-k8s-infra'
          access-token: ${{ secrets.ACCESS_KEY_GITHUB_INFRA }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Updates industry repository
        run: |
          cd starfoundry-k8s-infra/apps/industry;
          kustomize edit set image industry-api=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/api:${{ env.COMMIT_SHORT_SHA }}
          kustomize edit set image industry-collector=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/collector:${{ env.COMMIT_SHORT_SHA }}
          kustomize edit set image industry-event_worker=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/event-worker:${{ env.COMMIT_SHORT_SHA }}
          kustomize edit set image industry-meta-webserver=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/meta-webserver:${{ env.COMMIT_SHORT_SHA }}
          kustomize edit set image industry-web=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/web:${{ env.COMMIT_SHORT_SHA }}
      - name: Updates appraisal repository
        run: |
          cd starfoundry-k8s-infra/apps/appraisal;
          kustomize edit set image appraisal-api=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/api-appraisal:${{ env.COMMIT_SHORT_SHA }}
          kustomize edit set image appraisal-web=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/web-appraisal:${{ env.COMMIT_SHORT_SHA }}
          kustomize edit set image appraisal-meta-webserver=175554084336.dkr.ecr.eu-central-1.amazonaws.com/starfoundry/meta-webserver:${{ env.COMMIT_SHORT_SHA }}
      - name: Commit and push
        run: |
          cd starfoundry-k8s-infra
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit and push
        run: |
          cd starfoundry-k8s-infra
          git add -A
          git commit -m "Updates industry docker images to ${{ env.COMMIT_SHORT_SHA }}"
          git push origin main
