name: rust-tests

on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to a rust project that should be tested'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  check:
    name: test
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - name: Run cargo test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/for-testing
          STARFOUNDRY_STORE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/for-testing
        run: |
          cd ${{ inputs.folder }}
          cargo check

  test:
    name: test
    runs-on: [self-hosted, linux]
    needs: [check]
    steps:
      - uses: actions/checkout@master
      - name: Run cargo test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/for-testing
          STARFOUNDRY_STORE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/for-testing
        run: |
          cd ${{ inputs.folder }}
          sqlx migrate run
          cargo test
