name: store-webapp

on:
  push:
    branches:
      - main
      - rewrite
    paths:
      - webapp_store/**
  pull_request:
    paths:
      - webapp_store/**

concurrency:
  # Make sure every job on main has unique group id (run_id), so cancel-in-progress only affects PR's
  # https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  packages: write # for ghcr.io

jobs:
  test:
    uses: ./.github/workflows/common_webapp_test.yaml
    secrets: inherit
    with:
      folder: webapp_store

  build-image:
    uses: ./.github/workflows/common_build_docker.yaml
    secrets: inherit
    needs:
      - test
    with:
      name: store/webapp
      image: store-webapp
