name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: make docker-build

      - name: Trivy API
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{vars.DOCKER_REPO}}/starfoundry/api:${{ env.COMMIT_SHORT_SHA }}'
          format: 'sarif'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-api.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Trivy Event Worker
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{vars.DOCKER_REPO}}/starfoundry/event-worker:${{ env.COMMIT_SHORT_SHA }}'
          format: 'sarif'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-event-worker.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Trivy Web
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{vars.DOCKER_REPO}}/starfoundry/web:${{ env.COMMIT_SHORT_SHA }}'
          format: 'sarif'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-web.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Trivy Repo
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results-repository.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy api scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-api.sarif'
      - name: Upload Trivy api scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-event-worker.sarif'
      - name: Upload Trivy api scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-web.sarif'
      - name: Upload Trivy api scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-repository.sarif'
